name: Release

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}

      - name: Check lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Plugin zip
        run: yarn plugin-zip

      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.CI_GH_TOKEN }}
